---
 - name: Install Nmap using role on redhat
   import_tasks: nmap_cent.yml
   when: ansible_facts['os_family']|lower == 'redhat'

 - name: Install NMap using role on ubuntu 
   import_tasks: nmap_ubu.yml
   when: ansible_facts['os_family']|lower == 'debian'
...
